info:
  title: Blog Post API
  description: API Documentation for Blog Post API
  version: 1.0.0
openapi: 3.0.1
components:
  ## Här ligger mina scheman
  schemas:
    Key:
      type: string
      description: API Key
      example: blog-xxxxx
    Post:
      description: Post
      type: object
      properties:
        postId:
          type: string
          example: post-xxxxx
        userId:
          type: string
          example: user-xxxxx
        title:
          type: string
          example: Bla Bla
        text:
          type: string
          example: Bl BLa BLa BLa
    UserBody:
      description: User Body
      type: object
      properties:
        username:
          type: string
          example: jespernyberg
        password:
          type: string
          example: mysupersecretpassword
    PostBody:
      description: Post
      type: object
      properties:
        title:
          type: string
          example: Bla Bla
        text:
          type: string
          example: Bl BLa BLa BLa
  ## Här kommer mina responses
  responses:
    BadRequestError:
      description: Bad request from client
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Missing or invalid parameters in request
    NotFoundError:
      description: Requested resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: The requested resources was not found
paths:
  /api/keys:
    get:
      tags:
        - API Key
      description: Returns random API key
      responses:
        "200":
          description: Returns random API key
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  key:
                    type: string
                    example: blog-xxxxx
        "404":
          $ref: "#/components/responses/NotFoundError"
  /api/auth/logout:
    get:
      tags:
        - Auth
      description: Logout for user
      parameters:
        - in: query
          name: key
          required: true
          schema:
            $ref: "#/components/schemas/Key"
      responses:
        "200":
          description: Response for successful logout
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: User logged out successfully
        "404":
          $ref: "#/components/responses/NotFoundError"
  /api/auth/register:
    post:
      tags:
        - Auth
      description: Register new user
      parameters:
        - in: query
          name: key
          required: true
          schema:
            $ref: "#/components/schemas/Key"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/UserBody"
      responses:
        "200":
          description: Response for successful registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: User registered successfully
        "400":
          $ref: "#/components/responses/BadRequestError"
  /api/auth/login:
    post:
      tags:
        - Auth
      description: Login user
      parameters:
        - in: query
          name: key
          required: true
          schema:
            $ref: "#/components/schemas/Key"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/UserBody"
      responses:
        "200":
          description: Response for successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: User logged in successfully
        "400":
          $ref: "#/components/responses/BadRequestError"
  /api/posts:
    get:
      tags:
        - Posts
      description: Returns all posts
      parameters:
        - in: query
          name: key
          required: true
          schema:
            $ref: "#/components/schemas/Key"
      responses:
        "200":
          description: Response containing posts
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  posts:
                    type: array
                    items:
                      anyOf:
                        - $ref: "#/components/schemas/Post"
                        - $ref: "#/components/schemas/Post"
                        - $ref: "#/components/schemas/Post"
        "404":
          $ref: "#/components/responses/NotFoundError"
    post:
      tags:
        - Posts
      description: Returns all posts
      parameters:
        - in: query
          name: key
          required: true
          schema:
            $ref: "#/components/schemas/Key"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/PostBody"
      responses:
        "200":
          description: Response for successful post
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: New post added successfully
        "400":
          $ref: "#/components/responses/BadRequestError"
  /api/posts/{userId}:
    get:
      tags:
        - Posts
      description: Returns all posts from specific user
      parameters:
        - in: query
          name: key
          required: true
          schema:
            $ref: "#/components/schemas/Key"
        - in: path
          name: userId
          required: true
          schema:
            type: string
            example: user-xxxxx
      responses:
        "200":
          description: Response containing posts
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  posts:
                    type: array
                    items:
                      anyOf:
                        - $ref: "#/components/schemas/Post"
                        - $ref: "#/components/schemas/Post"
                        - $ref: "#/components/schemas/Post"
        "404":
          $ref: "#/components/responses/NotFoundError"
  /api/posts/{postId}:
    put:
      tags:
        - Posts
      description: Updates specific post
      parameters:
        - in: query
          name: key
          required: true
          schema:
            $ref: "#/components/schemas/Key"
        - in: path
          name: postId
          required: true
          schema:
            type: string
            example: post-xxxxx
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/PostBody"
      responses:
        "200":
          description: Response for successful updated post
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: New post updated successfully
        "400":
          $ref: "#/components/responses/BadRequestError"
    delete:
      tags:
        - Posts
      description: Deletes specific post
      parameters:
        - in: query
          name: key
          required: true
          schema:
            $ref: "#/components/schemas/Key"
        - in: path
          name: postId
          required: true
          schema:
            type: string
            example: post-xxxxx
      responses:
        "200":
          description: Response for successful deletion of post
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: New post deleted successfully
        "400":
          $ref: "#/components/responses/BadRequestError"
